Lots of work on v0.64 update:
-- Finished debugging based on the updates to the test suite with 
   nearly underflow and nearly overflow matrices.  Also the test suite
   was exapanded to match the one I've been using for v0.70 (with minor
   changes for the few syntax differences between the versions), and
   this found a few more bugs that I fixed.

-- Added some features that are present in the v0.70 development on the 
   trunk, but which weren't in v0.63:

   -- Permutation class

   -- TriRef

   -- m.sumElements(), m.sumAbsElements()

   -- m.unitUpperTri(), m.unitLowerTri()

   -- cView, fView

   -- version of MatrixViewOf with steps
   
-- Made Swap(m1,m2) and Swap(v1,v2) more efficient

-- (Re-)made SmallMatrixComposite inherit from MatrixComposite, so it
   can be automatically instantiated, allowing arbitrarily complicated
   expressions.  And the same with SmallVectorComposite.

-- Updated the documentation to include the changes for v0.64.

diff --git a/branches/v0.64/bin/tmv-version b/branches/v0.64/bin/tmv-version
--- a/branches/v0.64/bin/tmv-version
+++ b/branches/v0.64/bin/tmv-version
@@ -53,11 +53,16 @@ fi
 
 svnTag=$(echo "$svnURL" | sed 's,^$HeadURL: .*/tags/,,; s, \$$,,' | sed "s,/$MYNAME,,")
 if test -z "$svnTag" || $(echo "$svnTag" | grep -s -q '/') ; then
-    # Noisy failure:
-    # echo "NOTAG: unparseable $svnURL"
-    # Quiet failure:
-    echo "NOTAG: unparseable"
-    exit 1
+    # See if this is a branch rather than a tag:
+    svnTag=$(echo "$svnURL" | sed 's,^$HeadURL: .*/branches/,,; s, \$$,,' | sed "s,/$MYNAME,,")
+    if test -z "$svnTag" || $(echo "$svnTag" | grep -s -q '/') ; then
+
+        # Noisy failure:
+        # echo "NOTAG: unparseable $svnURL"
+        # Quiet failure:
+        echo "NOTAG: unparseable"
+        exit 1
+    fi
 fi
 
 echo $svnTag
